var SentenceData = {
  "lesson": 54,
  "text": "阿女含涙答\n蘭芝初還時\n府吏見丁寜\n結誓不别離\n今日違情義\n恐此事非奇\n自可斷來信\n徐徐更謂之\n阿母白媒人\n貧賤有此女\n始適還家門\n不堪吏人婦\n豈合令郎君\n幸可廣問訊\n不得便相許\n媒人去數日\n尋遣丞請還\n説有蘭家女\n承籍有宦官\n云有第五郎\n蘭芝仰頭答\n理實如兄言\n謝家事夫婿\n中道還兄門\n處分適兄意\n那得自任專\n雖與府吏要\n渠會永無緣\n矯逸未有婚\n遣丞為媒人\n主簿通語言\n直説太守家\n有此令郎君\n既欲結大義\n故遣來貴門\n阿母謝媒人\n女子先有誓\n老姥豈敢言\n阿兄得聞之\n悵然心中煩\n舉言謂阿妹\n作計何不量\n先嫁得府吏\n後嫁得郎君\n否泰如天地\n足以榮汝身\n不嫁異郎體\n其往欲何云\n登即相許和\n便可作婚婣\n媒人下床去\n諾諾複爾爾\n還部白府君\n下官奉使命\n言談大有緣",
  "sentences": [
    { "number": 1, "original": "阿女含涙答", "transliteration": "", "translation": "But with tears she answered her mother:" },
    { "number": 2, "original": "蘭芝初還時", "transliteration": "", "translation": "«Lan Zhi just returned home recently!" },
    { "number": 3, "original": "府吏見丁寜", "transliteration": "", "translation": "The official instructed me when we parted," },
    { "number": 4, "original": "結誓不别離", "transliteration": "", "translation": "And I myself swore not to be separated." },
    { "number": 5, "original": "今日違情義", "transliteration": "", "translation": "I won't violate my loyalty to him." },
    { "number": 6, "original": "恐此事非奇", "transliteration": "", "translation": "Giving consent - that would be unworthy." },
    { "number": 7, "original": "自可斷來信", "transliteration": "", "translation": "I'll give the matchmaker a decisive refusal," },
    { "number": 8, "original": "徐徐更謂之", "transliteration": "", "translation": "I'll say it's too early to speak of this.»" },
    { "number": 9, "original": "阿母白媒人", "transliteration": "", "translation": "And politely the mother said to the matchmaker:" },
    { "number": 10, "original": "貧賤有此女", "transliteration": "", "translation": "«No, my daughter is poor and unworthy," },
    { "number": 11, "original": "始適還家門", "transliteration": "", "translation": "And her first husband sent her back home." },
    { "number": 12, "original": "不堪吏人婦", "transliteration": "", "translation": "She's not a match for a minor official -" },
    { "number": 13, "original": "豈合令郎君", "transliteration": "", "translation": "Would she suit your noble son?»" },
    { "number": 14, "original": "幸可廣問訊", "transliteration": "", "translation": "Days pass since the matchmaker left," },
    { "number": 15, "original": "不得便相許", "transliteration": "", "translation": "And I, an old woman, don't dare to decide.»" },
    { "number": 16, "original": "媒人去數日", "transliteration": "", "translation": "Days pass since the matchmaker left," },
    { "number": 17, "original": "尋遣丞請還", "transliteration": "", "translation": "The county magistrate sends him again" },
    { "number": 18, "original": "説有蘭家女", "transliteration": "", "translation": "The matchmaker appeared again at the Liu family:" },
    { "number": 19, "original": "承籍有宦官", "transliteration": "", "translation": "This one is the son of a high official:" },
    { "number": 20, "original": "云有第五郎", "transliteration": "", "translation": "To say that his fifth son is handsome," },
    { "number": 21, "original": "蘭芝仰頭答", "transliteration": "", "translation": "Lan Zhi respectfully answered him:" },
    { "number": 22, "original": "理實如兄言", "transliteration": "", "translation": "«My brother speaks fairly to his sister." },
    { "number": 23, "original": "謝家事夫婿", "transliteration": "", "translation": "I, leaving my husband's family," },
    { "number": 24, "original": "中道還兄門", "transliteration": "", "translation": "As duty demands, came to my father's house" },
    { "number": 25, "original": "處分適兄意", "transliteration": "", "translation": "And should act according to my brother's wishes," },
    { "number": 26, "original": "那得自任專", "transliteration": "", "translation": "I don't dare to be willful." },
    { "number": 27, "original": "雖與府吏要", "transliteration": "", "translation": "Although I gave a vow to the official," },
    { "number": 28, "original": "渠會永無緣", "transliteration": "", "translation": "But perhaps we're not destined to meet," },
    { "number": 29, "original": "矯逸未有婚", "transliteration": "", "translation": "But he hasn't married yet." },
    { "number": 30, "original": "遣丞為媒人", "transliteration": "", "translation": "The matchmaker appeared again at the Liu family:" },
    { "number": 31, "original": "主簿通語言", "transliteration": "", "translation": "And now he sent me to your gates.»" },
    { "number": 32, "original": "直説太守家", "transliteration": "", "translation": "«In the governor's family there's a handsome son," },
    { "number": 33, "original": "有此令郎君", "transliteration": "", "translation": "This one is the son of a high official:" },
    { "number": 34, "original": "既欲結大義", "transliteration": "", "translation": "He wants to perform an important ceremony" },
    { "number": 35, "original": "故遣來貴門", "transliteration": "", "translation": "And now he sent me to your gates.»" },
    { "number": 36, "original": "阿母謝媒人", "transliteration": "", "translation": "The mother modestly replied to the matchmaker:" },
    { "number": 37, "original": "女子先有誓", "transliteration": "", "translation": "«The girl bound herself with a vow to her husband," },
    { "number": 38, "original": "老姥豈敢言", "transliteration": "", "translation": "And I, an old woman, don't dare to decide.»" },
    { "number": 39, "original": "阿兄得聞之", "transliteration": "", "translation": "Lan Zhi's brother intervened with bitter annoyance" },
    { "number": 40, "original": "悵然心中煩", "transliteration": "", "translation": "Lan Zhi's brother intervened with bitter annoyance" },
    { "number": 41, "original": "舉言謂阿妹", "transliteration": "", "translation": "And, turning to his sister, said:" },
    { "number": 42, "original": "作計何不量", "transliteration": "", "translation": "«Don't be imprudent in your decisions:" },
    { "number": 43, "original": "先嫁得府吏", "transliteration": "", "translation": "Your husband was an insignificant official," },
    { "number": 44, "original": "後嫁得郎君", "transliteration": "", "translation": "But this one is the son of a high official:" },
    { "number": 45, "original": "否泰如天地", "transliteration": "", "translation": "Like heaven and earth, they are different." },
    { "number": 46, "original": "足以榮汝身", "transliteration": "", "translation": "Know that with a new husband glory awaits you," },
    { "number": 47, "original": "不嫁異郎體", "transliteration": "", "translation": "You're missing a noble husband." },
    { "number": 48, "original": "其往欲何云", "transliteration": "", "translation": "Tell me, what do you expect and want?»" },
    { "number": 49, "original": "登即相許和", "transliteration": "", "translation": "And I agree to enter a new marriage.»" },
    { "number": 50, "original": "便可作婚婣", "transliteration": "", "translation": "And, confirming the agreement again," },
    { "number": 51, "original": "媒人下床去", "transliteration": "", "translation": "The matchmaker hurriedly got up from his seat, satisfied" },
    { "number": 52, "original": "諾諾複爾爾", "transliteration": "", "translation": "And, confirming the agreement again," },
    { "number": 53, "original": "還部白府君", "transliteration": "", "translation": "He hurried to report to the governor:" },
    { "number": 54, "original": "下官奉使命", "transliteration": "", "translation": "«I, unworthy, have fulfilled the order." },
    { "number": 55, "original": "言談大有緣", "transliteration": "", "translation": "Fate is favorable for entering into marriage.»" }
  ]
};